[font]
# Font configuration
    normal = { family = "FiraCode Nerd Font", style = "Regular" }
    size = 14.0

[window]
    padding = {x = 10, y = 10}
    opacity = 0.8

[keyboard]
    bindings = [{key = "Return", mods = "Super|Shift", command = "alacritty"},
                {key = "Space", mods = "Control", mode = "~vi", action = "ToggleViMode"}]

# Default colors
[colors.primary]
background = "#00011D"
foreground = '#cccccc'

# Normal colors
[colors.normal]
black      = '#0c0c0c'
red        = '#c50f1f'
green      = '#05f00d'
yellow     = '#c19c00'
blue       = '#0037da'
magenta    = '#881798'
cyan       = '#3a96dd'
white      = '#cccccc'

# Bright colors
[colors.bright]
black      = '#767676'
red        = '#e74856'
green      = '#16c60c'
yellow     = '#f9f1a5'
blue       = '#3b78ff'
magenta    = '#b4009e'
cyan       = '#61d6d6'
white      = '#f2f2f2'
